# Generated by Django 4.1.4 on 2023-01-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PMStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PMStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.URLField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStreamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStreamImpStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_start_date', models.DateField(null=True)),
                ('rm_end_date', models.DateField(null=True)),
                ('fact_start_date', models.DateField(null=True)),
                ('fact_end_date', models.DateField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('imp_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.impstage')),
                ('project_stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.projectstream')),
            ],
        ),
        migrations.AddField(
            model_name='projectstream',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.projectstreamstatus'),
        ),
        migrations.CreateModel(
            name='ProjectReportImpStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('imp_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.impstage')),
                ('project_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.projectreport')),
            ],
        ),
        migrations.AddField(
            model_name='projectreport',
            name='project_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.projectstream'),
        ),
        migrations.CreateModel(
            name='ProjectPMStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('pm_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.pmstep')),
                ('project_pm_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.pmstage')),
            ],
        ),
    ]
