# Generated by Django 4.1.4 on 2023-01-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_product_industry_product_category'),
    ]

    operations = [

        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.projectstatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.projecttype'),
        ),
    ]
