# Generated by Django 4.1.4 on 2023-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_project_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_months',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
