# Generated by Django 4.1.4 on 2023-01-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_projectpmstage_alter_projectpmstep_project_pm_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpmstage',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm.project'),
            preserve_default=False,
        ),
    ]
