# Generated by Django 4.1.4 on 2023-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_projectpmstage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpmstage',
            name='invoice_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
