# Generated by Django 4.1.4 on 2023-01-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_projectpmstage_pm_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='category_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='source_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
