# Generated by Django 4.1.4 on 2023-01-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_projectreport_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='impstage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pmstage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pmstep',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectpmstage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectpmstep',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectreport',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectreportimpstage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectstream',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectstreamimpstage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectstreamstatus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectteam',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['id']},
        ),
    ]
