# Generated by Django 4.1.4 on 2023-01-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_client_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
    ]
