# Generated by Django 4.1.4 on 2023-01-13 12:25

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=crm.models.project_report_file_name),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Supplier name', max_length=255),
        ),
    ]
