# Generated by Django 4.1.4 on 2023-02-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_supplier_options_alter_projectreport_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='comment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.product'),
        ),
        migrations.AddField(
            model_name='lead',
            name='proposal_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.agent'),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_stage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.leadstage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.leadsource'),
        ),
        migrations.AddField(
            model_name='lead',
            name='reason_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.reason'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sales_manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.salesmanager'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.leadstatus'),
        ),
    ]
