# Generated by Django 4.1.4 on 2023-02-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_contractor_address_remove_contractor_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='bin',
            field=models.CharField(max_length=20),
        ),
    ]
