# Generated by Django 4.1.4 on 2023-02-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_contractor_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='current_stage_id',
            new_name='current_stage',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='lead_source_id',
            new_name='lead_source',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='reason_id',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='sales_manager_id',
            new_name='sales_manager',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='status_id',
            new_name='status',
        ),
    ]
