# Generated by Django 4.1.4 on 2023-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_rename_agent_id_lead_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='comment_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
