# Generated by Django 4.1.4 on 2023-02-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_client_client_header_alter_client_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.project'),
        ),
    ]
