# Generated by Django 4.1.4 on 2023-02-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_contract_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.contractor'),
        ),
    ]
