# Generated by Django 4.1.4 on 2023-02-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_contract_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmstage',
            name='descriptor',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
