# Generated by Django 4.1.4 on 2023-02-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_pmstage_descriptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmstage',
            old_name='descriptor',
            new_name='stage_descriptor',
        ),
    ]
