# Generated by Django 4.1.4 on 2023-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_client_client_header_alter_client_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpmstage',
            name='fact_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpmstage',
            name='fact_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpmstage',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectpmstage',
            name='rm_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpmstage',
            name='rm_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpmstage',
            name='ts_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpmstage',
            name='ts_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
