# Generated by Django 4.1.4 on 2023-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_projectpmstage_fact_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmstage',
            name='stage_descriptor',
        ),
        migrations.AddField(
            model_name='pmstage',
            name='required_for_project',
            field=models.BooleanField(default=False),
        ),
    ]
