# Generated by Django 4.1.4 on 2023-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_remove_pmstage_stage_descriptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impstage',
            name='required_for_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impstage',
            name='required_for_stream',
            field=models.BooleanField(default=False),
        ),
    ]
