# Generated by Django 4.1.4 on 2023-02-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_alter_project_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpmstep',
            name='project_pm_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.projectpmstage'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='project_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.projectstream'),
        ),
        migrations.AlterField(
            model_name='projectreportimpstage',
            name='project_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.projectreport'),
        ),
        migrations.AlterField(
            model_name='projectstream',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.project'),
        ),
        migrations.AlterField(
            model_name='projectstreamimpstage',
            name='project_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.projectstream'),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.project'),
        ),
    ]
