# Generated by Django 4.1.4 on 2023-03-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmstage',
            name='final_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='final_status',
            field=models.BooleanField(default=False),
        ),
    ]
